const fs = require('node:fs');
const path = require('node:path');
const model = require('../dist/catalog-model.js');
const mapLocations = require('./map-locations.cjs');
const root = path.join(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, 'data', name), 'utf8'));
const settings = read('settings.json');
const registry = read('organisations.json');
const websites = read('organisation-websites.json');
const profiles = read('organisation-profiles.json');
for (const org of registry.organisations) {
  const website = websites.organisations[org.name];
  if (website === undefined) throw new Error(`Missing website review: ${org.name}`);
  if (website) {
    const parsed = new URL(website.url);
    if (parsed.protocol !== 'https:' || parsed.username || parsed.password || !['about', 'home'].includes(website.type)) {
      throw new Error(`Unsafe organisation website for ${org.name}`);
    }
  }
  org.website = website;
  const profile = profiles.organisations[org.name];
  if (profile === undefined) throw new Error(`Missing organisation profile review: ${org.name}`);
  if (profile) {
    const source = new URL(profile.sourceUrl);
    if (source.protocol !== 'https:' || source.username || source.password || !profile.description?.trim() || profile.description.length > 450) {
      throw new Error(`Invalid organisation profile: ${org.name}`);
    }
  }
  org.profile = profile;
}
const records = settings.mode === 'demo' ? read('demo-opportunities.json') : require('./research-records.cjs').readRecords(root);
model.validate(records, registry, settings);
const now = new Date();
// Unapproved audit candidates stay in data/ and private CLI compilations, outside the published assets.
const gazetteer = read('map-cities.json');
mapLocations.validateGazetteer(gazetteer);
const publication = model.selectPublic(records, settings, now);
const publicRecords = [...publication.opportunities, ...publication.confirmedFuture].map(record => {
  const mapLocation = mapLocations.cityLocation(record, gazetteer);
  return mapLocation ? {...record, mapLocation} : record;
});
const selected = model.selectPublic(publicRecords, settings, now);
const catalog = { ...selected, records: publicRecords, settings, publicScope:'current-and-upcoming', generatedAt: now.toISOString() };
fs.writeFileSync(path.join(root, 'dist/catalog.js'), '// Generated by node scripts/build.cjs. Edit data/*.json instead.\nconst radarCatalog = '+JSON.stringify(catalog)+';\n');
fs.writeFileSync(path.join(root, 'dist/organisations.js'), '// Organisation links do not verify opportunity availability.\nconst radarRegistry = '+JSON.stringify(registry)+';\n');
console.log(`${settings.mode}: ${registry.organisations.length} organisations, ${selected.opportunities.length} accepting vacancies/registers, ${selected.confirmedFuture.length} verified upcoming through ${selected.publicOpeningWindow.through}, ${selected.opportunities.filter(item=>item.mapLocation).length} current city markers; ${model.select(records,settings,now).futureCompilation.length} future records retained offline.`);
