const fs = require('node:fs');
const path = require('node:path');
const model = require('../dist/catalog-model.js');
const root = path.join(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, 'data', name), 'utf8'));
const settings = read('settings.json');
const registry = read('organisations.json');
const records = read(settings.mode === 'demo' ? 'demo-opportunities.json' : 'live-opportunities.json');
model.validate(records, registry, settings);
const now = new Date();
// Unapproved audit candidates stay in data/ and private CLI compilations, outside the published assets.
const publicRecords = records.filter(record => record.publicationApproved !== false);
const selected = model.select(publicRecords, settings, now);
const catalog = { ...selected, records: publicRecords, settings, generatedAt: now.toISOString() };
fs.writeFileSync(path.join(root, 'dist/catalog.js'), '// Generated by node scripts/build.cjs. Edit data/*.json instead.\nconst radarCatalog = '+JSON.stringify(catalog)+';\n');
fs.writeFileSync(path.join(root, 'dist/organisations.js'), '// Imported reference URLs have not been checked.\nconst radarRegistry = '+JSON.stringify(registry)+';\n');
console.log(`${settings.mode}: ${registry.organisations.length} organisations, ${selected.opportunities.length} open programs, ${selected.confirmedFuture.length} confirmed future, ${selected.recurringUnconfirmed.length} recurring unconfirmed, ${selected.futureCompilation.length} retained for future compilation, ${selected.excluded.length} held back.`);
